CHANGELOG.md, node/resolvers/index.ts
This PR treats users from "inactive" or "on hold" organizations the same as users who do not have the "can-checkout" permission. In other words a user's organization must be active for them to be able to place an order.
Linked in https://quotes--sandboxusdev.myvtex.com for testing
=> [B2BORG-19] Block checkout if user's org is not active

.prettierignore, CHANGELOG.md, checkout-ui-custom/checkout6-custom.css, checkout-ui-custom/checkout6-custom.js
This PR employs a slightly different usage of CSS to show/hide the appropriate payment methods in the B2B checkout.
New version is linked in https://quotes--sandboxusdev.myvtex.com
Before:
After:
=> Improve display of payment methods

CHANGELOG.md, checkout-ui-custom/checkout6-custom.css, checkout-ui-custom/checkout6-custom.js
The previous PR https://github.com/vtex-apps/b2b-checkout-settings/pull/8 had the unintended effect of making the checkout payment method filtering only work when: 
- the Checkout UI Custom "show payment methods as accordions" option was selected, and
- the B2B Checkout Settings JS was injected AFTER the Checkout UI Custom JS
Since we have no direct control over the order in which multiple checkout JS apps inject their JS, this PR aims to make the feature work regardless of which layout option is used, and which order JS is injected in.
This new version is linked in https://arthur--b2bstoreqa.myvtex.com
This is what it looks like: 
TABBED
ACCORDION
For the accordion formatting, note that there is still some weird extra spacing where the disabled payment methods are, but we may need to …
=> [B2BCHCKOUT-13] Fix display of payment terms

CHANGELOG.md, checkout-ui-custom/checkout6-custom.css, checkout-ui-custom/checkout6-custom.js
Added a new feature to check if the order form has a custom data property ("b2b-quotes-graphql") from quotes and then the items in the cart will be locked by .item-disabled css class which disables the pointer events from mouse/touch.
According to the [B2BCHCKOUT-11](https://vtex-dev.atlassian.net/browse/B2BCHCKOUT-11), when the cart comes from a quote, it must be locked, so, the solution was provided by a JS & css locking the elements from the cart.
This feature has been linked on this URL [https://artur--b2bstoreqa.myvtex.com/](https://artur--b2bstoreqa.myvtex.com/).
1) Access the url: [https://artur--b2bstoreqa.myvtex.com](https://artur--b2bstoreqa.myvtex.com)
2) Go to this url: [https://artur--b2bstoreqa.myvtex.com/b2b-quotes](https://artur--b2bstoreqa.myvtex.com/b2b-quotes)
3) Use …
=> B2BCHCKOUT-11

CHANGELOG.md, checkout-ui-custom/checkout6-custom.js, node/resolvers/index.ts
When the new 1.x major of this app was released, the `checkUserPermission` graphQL query stopped working because the `sender` property was still set to `vtex.b2b-checkout-settings@0.x` instead of 1.x. This PR fixes the problem.
I also added an additional null check to checkout6-custom.js as I noticed a type error was sporadically being thrown in checkout.
New version linked here: https://b2bsuite--sandboxusdev.myvtex.com
=> Fix graphql sender version

CHANGELOG.md, checkout-ui-custom/checkout6-custom.css
This is a simple PR that applies `!important` to the show/hide payment term CSS rules. This fixes an issue where CSS injected into checkout by checkout-ui-custom was overriding the b2b-checkout-settings CSS and causing disabled payment terms to be displayed to the user.
I will also open a PR for the 1.x major.
New version linked here: https://arthur--b2bstoreqa.myvtex.com/
=> [B2BCHCKOUT-12] Fix payment terms CSS (0.x)

CHANGELOG.md, docs/README.md
The images in the documentation were broken after the PR was merged. This PR fixes their links.
=> Fixing documentation image links

CHANGELOG.md, checkout-ui-custom/checkout6-custom.js
Related to https://github.com/vtex-apps/b2b-organizations-graphql/pull/21
As we have decided to allow organizations to use the Credit Card payment method (if assigned to that particular org), this PR adds some logic to support this. The method we're using to find the payment methods that should be enabled needed to be adjusted because the `innerText` of the Credit Card selector has more text than just "Credit Card". Therefore instead of an exact comparison, the app now checks if the inner text STARTS with "Credit card". 
New version linked here: https://b2bsuite--sandboxusdev.myvtex.com
=> [B2BORG-83] Add support for enabling Credit Card payment method

CHANGELOG.md, checkout-ui-custom/checkout6-custom.js, node/resolvers/index.ts
Previously our checkout JS was comparing the "innerText" of each checkout payment method div against the payment methods assigned to the user's organization. However, in non-US stores, the innerText is likely a localized version of the payment method name and not the exact string that has been assigned to the organization. Therefore, this PR changes the matching logic to look at the div's `data-name` attribute where the original non-intl name is stored.
This PR also adjusts the checkout JS to ensure that the payment method logic runs after the payment method divs have been rendered.
It also allows the `b2bCheckoutSettings` to be returned if telemarketing impersonation is active and the original user is not logged in. It does this by only requiring the `storeUserAuthToken` if the host does …
=> Support intl payment method names

.github/workflows/sonarcloud.yml, CHANGELOG.md, checkout-ui-custom/checkout6-custom.js
- The current use of sessionStorage for user impersonation needs to be improved;
- This is related to what Sofia was reporting this morning while testing telemarketing app impersonation;
It was added a time expiration by 5 minutes to b2b-checkout-settings session storage key.
Before the checkout rendering, it checks if it exists and the time expiration and then removes the settings in order to renew by calling the API;
It's linked on: [https://b2borg--sandboxusdev.myvtex.com/](https://b2borg--sandboxusdev.myvtex.com/)
It's pretty hard to test once there is a flag preventing the tests:
```ts
if (isWorkspace() || !settings) {
```
line: 378
To test it properly, I suggest you check out the branch in your own machine, remove the isWorkscape() function from the conditional statement, and then …
=> [B2BCHCKOUT-22] Improve handling for impersonation expiration

CHANGELOG.md, checkout-ui-custom/checkout6-custom.js
Fix a bug on checking impersonation email expiration
PR Related: [B2BCHCKOUT-22]
https://github.com/vtex-apps/b2b-checkout-settings/pull/22
Ability to prevent a quote from being updated during checkout flow - Lock interface and can’t change quantity feature not working fine
- Create quote/Open Existing quote
- Click Use quote button
- Then try to update product quantity
Actual Result: Able to update product quantity
Expected Result: Should not allow to update product quantity
I found a bug related to the PR mentioned above, it was checking the email comparing the wrong variable, it was triggering an error and stopping the b2b checkout;
Workspace: [https://b2b1863508--productusqa.myvtex.com/](https://b2b1863508--productusqa.myvtex.com/)
=> [B2BQUOTES-51] Ability to prevent a quote from being updated during checkout flow - Lock interface and can’t change quantity feature not working fine

CHANGELOG.md, checkout-ui-custom/checkout6-custom.js, node/service.json
**What problem is this solving?**
In production (live domains), the endpoint `/b2b-checkout-settings/` returns `User not authenticated` even when the user is logged in. This does not happen in `myvtex` sites and may be caused by undefined `storeUserAuthToken`. I'm prefixing the route with `/_v/private` in order to use `storeUserAuthToken`.
**How to test it?**
I linked changes in workspace [anna](https://anna--marketplace3m.myvtex.com/) in account marketplace3m and tried to access the b2b checkout settings:
https://shop.metalinspec.com.mx/_v/private/b2b-checkout-settings?workspace=anna
https://shop.metalinspec.com.mx/b2b-checkout-settings?workspace=master
=> [B2BORG-124] Fix bug getting b2b checkout settings info for logged in users in production domains

CHANGELOG.md, checkout-ui-custom/checkout6-custom.js, node/resolvers/Routes/index.ts
Currently non-B2B users don't have access to checkout when B2B Checkout Settings is installed. They don't have a role and so they don't have the permission `can-checkout` in their settings. This PR doesn't apply b2b settings for users who don't have an associated organization or cost center, allowing them to access the checkout.
Test in workspace [annab2bcheckout](https://annab2bcheckout--sandboxusdev.myvtex.com/).
In this workspace, I removed access to the checkout for users with Admin role. Add a new user with Admin access to any organization (e.g [this](https://annab2bcheckout--sandboxusdev.myvtex.com/admin/b2b-organizations/organizations/e9188242-e373-11ec-835d-0e08deb41249/#/users)). Go to store site > Login as B2B Organization Admin user > Add item to cart > Try to checkout > see …
=> [B2BCHCKOUT-29] Allow non-B2B users to access checkout

CHANGELOG.md, checkout-ui-custom/checkout6-custom.css, checkout-ui-custom/checkout6-custom.js
Display profile editing option, all payment methods, and buttons to edit/add shipping addresses for non-B2B users.
Test in workspace [annab2bcheckout](https://annab2bcheckout--sandboxusdev.myvtex.com/).
Try checking out as a non-B2B user and you should be able to edit the Profile section, edit or add addresses in Shipping, and see all payment methods from the store in Payment.
=> [B2BCHCKOUT-29] Fix hidden shipping and payment CSS for non-B2B users

CHANGELOG.md, vtex.storefront-permissions/configuration.json
- Currently in the checkout we should allow users to be able to create a new address based on their roles
- Allow users to create a new address if they have a specific role
This can be tested [here](https://alberto--vysk.myvtex.com/)
**Steps to reproduce:**
1. Login using credentials: 
2. 
```
jose.basilio@vtex.com
Testing1234
```
3. Add a product to the cart
4. Proceed to shipping method
5. Edit address
6. This address should be saved when checking out 
hot of changes:
=> Update roles in order to let user create address in checkout

CHANGELOG.md, checkout-ui-custom/checkout6-custom.js
- Add checkout settings to in the paymentStep if they do not exist.
When users have the change address added to their storeFront Permissions, the b2bCheckout settings object is removed. This not allowing paymentTerms settings for the organization not to render.
You can test [here](https://albertoo--sandboxusdev.myvtex.com/checkout/#/payment)
=> Add b2bCheckoutSettings on payment

CHANGELOG.md, checkout-ui-custom/checkout6-custom.js
At the end of the checkout UI Custom js there was a semicolon missing that is causing issues with build.
=> Added semicolon to the checkout6 as it was causing an issue with build

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/qe-pull-request-target.yml, .github/workflows/qe-pull-request.yml, .github/workflows/qe-push.yml, .vtexignore, CHANGELOG.md, node/jest.config.ts, node/package.json, node/resolvers/Routes/index.test.ts, node/resolvers/Routes/index.ts, node/tsconfig.json, node/yarn.lock, package.json, react/components/B2BCheckoutAdmin.tsx, sonar-project.properties, yarn.lock
It was found a bug in checkout payment where the payment method is showing even when disabled on cost center.
I found the request to _v/private/b2b-checkout-settings on checkout and it responded with the payment terms from the organization instead of the cost center.
#changingTooling
- Access the My Organization in My Account with an "Organization Admin" role;
- Click on the Cost Center; 
- In the "Payment Terms" section, deactivate a payment term;
- Access the checkout and go to Payment; the deactivated option is still available.
[Workspace](https://b2bteam1244--b2bstore005.myvtex.com/)
It was considered to disable the payment terms for the organization, but it would be impractical.
=> hotfix: get payments terms from cost center

CHANGELOG.md, node/clients/StorefrontPermissions.ts, node/clients/index.ts
We broker some B2B stores that have the app, because in the checkout page is showing the message "Acesso - Você não tem acesso ao checkout"
- Go to checkout page with some product and continue to payment
[Workspace](https://security--b2bsuite.myvtex.com/)
=> fix: adjust app name to get permission and token header

CHANGELOG.md, node/package.json, node/resolvers/Routes/index.test.ts, node/resolvers/Routes/index.ts, node/yarn.lock
Updating payment terms in the organization details UI does not apply to B2B checkout settings.
This behavior occurs because the update occurs only for the organization, but B2B checkout settings use cost center information, which is not updated by the organization details UI.
* Create an organization;
* In the organization details UI, update the payment terms;
* Access the website, assemble a cart and access checkout; Payment terms will remain the same.
[Workspace](https://icaroov--b2bstore005.myvtex.com/checkout/#/cart)
=> fix: Payment Terms changes not applied in the B2B Checkout Settings

CHANGELOG.md, node/clients/index.ts
Provide app token on calls to b2b-organizations-graphql instead of admin/user tokens as these were already validated at this point. More details on: [https://vtex-dev.atlassian.net/browse/B2BTEAM-1797](https://vtex-dev.atlassian.net/browse/B2BTEAM-1797)
=> fix: provide app token on calls to b2b-organizations-graphql app
